# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Create Resource Group
description: --

runs:
  using: "composite"
  steps:
    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          az group create --location ${{ env.location }} --name ${{ env.terraform_st_resource_group }}
