name: terraform
summary: Terraform example for Lab 3 - Data Analytics with Databricks
description: Deploys an environment using Terraform containing a resource group
runner: Terraform
templatePath: main.tf
parameters: 
- id: "prefix"
  name: "Prefix"
  type: "string"
  required: true
- id: "postfix"
  name: "Postfix"
  type: "string"
  required: true
- id: "location"
  name: "Location"
  default: "centralus"
  type: "string"
- id: "enable_private_endpoints"
  name: "enable_private_endpoints"
  default: "false"
  type: "string"
- id: "public_network_enabled"
  name: "public_network_enabled"
  default: "true"
  type: "string"
- id: "enable_ip_access_list"
  name: "enable_ip_access_list"
  default: "false"
  type: "string"
- id: "enable_jumphost"
  name: "enable_jumphost"
  default: "false"
  type: "string"
- id: "enable_data_factory"
  name: "enable_data_factory"
  default: "false"
  type: "string"
- id: "enable_event_hub_namespace"
  name: "enable_event_hub_namespace"
  default: "false"
  type: "string"
- id: "enable_cosmosdb"
  name: "enable_cosmosdb"
  default: "false"
  type: "string"
- id: "enable_data_explorer"
  name: "enable_data_explorer"
  default: "false"
  type: "string"
- id: "jumphost_username"
  name: "Jumphost Username"
  default: "adladmin"
  type: "string"
- id: "jumpbox_password"
  name: "Jumpbox Password"
  default: "P@ssw0rd1234!"
  type: "string"