# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  prefix: "adl03"
  postfix: "101"
  location: "northeurope"

  # Feature flags
  enable_private_endpoints: "true"
  public_network_enabled : "true"
  enable_ip_access_list: "true"
  enable_jumphost: "true"
  enable_data_factory: "true"
  enable_event_hub_namespace: "true"
  enable_cosmosdb: "true"
  enable_data_explorer: "true"

  # Jumphost settings
  jumphost_username: "adladmin"
  jumpbox_password: "P@ssw0rd1234!"

  # Terraform remote storage
  terraform_st_resource_group: rg-adl-terraform-state
  terraform_st_storage_account: stadlterraformstate
  
  # Internals - do not touch
  az_cli_version: 2.45.0
  terraform_st_container_name: default
