# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  prefix: "adl03"
  postfix: "101"
  location: "northeurope"

  # Feature flags
  enable_private_endpoints: "false"
  public_network_enabled : "false"
  enable_ip_access_list: "false"
  enable_jumphost: "false"
  enable_data_factory: "false"
  enable_event_hub_namespace: "false"
  enable_cosmosdb: "false"
  enable_data_explorer: "false"

  # Enable ADE based deployment
  enable_ade_deployment: "true"

  # Terraform remote storage
  terraform_st_resource_group: rg-adl-terraform-state
  terraform_st_storage_account: stadlterraformstate
  
  # Internals - do not touch
  az_cli_version: 2.45.0
  terraform_st_container_name: default
