# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Terraform Apply
description: --

runs:
  using: "composite"
  steps:
    - name: Terraform Apply
      run: terraform apply -auto-approve -var "location=${{ env.location }}" -var "prefix=${{ env.prefix }}" -var "postfix=${{ env.postfix }}"
      working-directory: ${{ env.terraform_workingdir }} 
      shell: bash
