# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Parse Terraform Environment Variables
description: --

runs:
  using: "composite"
  steps:
    - name: Parse Terraform Environment Variables
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: | 
        # Parse Azure secret into Terraform variables
        $servicePrincipal = ($env:AZURE_CREDENTIALS | ConvertFrom-Json)
        $env:ARM_CLIENT_ID = $servicePrincipal.clientId
        $env:ARM_CLIENT_SECRET = $servicePrincipal.clientSecret
        $env:ARM_SUBSCRIPTION_ID = $servicePrincipal.subscriptionId
        $env:ARM_TENANT_ID = $servicePrincipal.tenantId
        echo "::add-mask::$env:ARM_CLIENT_ID"
        echo "::add-mask::$env:ARM_CLIENT_SECRET"
        echo "::add-mask::$env:ARM_SUBSCRIPTION_ID"
        echo "::add-mask::$env:ARM_TENANT_ID"
        # Save environment variable setup for subsequent steps
        Get-ChildItem -Path Env: -Recurse -Include ARM_*,TF_VAR_* | ForEach-Object {Write-Output "$($_.Name)=$($_.Value)"} >> $env:GITHUB_ENV
      shell: pwsh
