# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  prefix: "adl-01"
  postfix: "12n"
  location: "northeurope"

  terraform_st_resource_group: rg-adl-terraform-state
  terraform_st_storage_account: stadlterraformstate

  # Feature flags
  enable_private_endpoints: "false"
  enable_jumphost: "false"
  enable_analysis_services_server: "true"
  enable_data_factory: "true"
  enable_synapse_sql_pool: "true"
  enable_synapse_spark_pool: "true"

  # Internals - do not touch
  az_cli_version: 2.36.0
  terraform_st_container_name: default
