# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Set Environment Variables
description: --

inputs:
  variablesPath:
    description: "The path to the YAML file that contains the key value pairs for environment variables"
    required: true

runs:
  using: "composite"
  steps:

    # [Setup] task(s)
    # ---------------
    - name: "Setup agent"
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Setup agent"
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE '.github' 'utils' 'Set-EnvironmentOnAgent.ps1')
        # Define PS modules to install on the runner
        $Modules = @(
            @{ Name = 'powershell-yaml'; Version = '0.4.2'}
        )
        # Set agent up
        Set-EnvironmentOnAgent -PSModules $Modules
        Write-Output "::endgroup::"

    # [Set environment variables] task(s)
    # ---------------
    - name: "Set environment variables"
      id: set-env-variables
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Set environment variables"
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE '.github' 'utils' 'Add-YamlListToFile.ps1')
        $functionInput = @{
          InputFilePath   = '${{ inputs.variablesPath }}'
          ListName        = 'variables'
          OutputFilePath  =  $Env:GITHUB_ENV
        }
        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
        # Convert YAML Variable File to Environment Variables
        Add-YamlListToFile @functionInput -Verbose
        Write-Output "::endgroup::"
